#! /bin/sh
### BEGIN INIT INFO
# Provides: frontend-server
# Required-Start: $docker
# Required-Stop: $docker
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Frontend Server
# Description: This file starts and stops Simpliflow Frontend Server
#
### END INIT INFO

## This file is NOT automatically synced.
## If you change this you will have to
## update the AMI

case "$1" in
 start)
   su ubuntu -l -c /home/ubuntu/startup_server.sh
   ;;
 stop)
   su ubuntu -l -c /home/ubuntu/stop_server.sh
   ;;
 restart)
   su ubuntu -l -c /home/ubuntu/stop_server.sh
   sleep 10
   su ubuntu -l -c /home/ubuntu/startup_server.sh
   ;;
 *)
   echo "Usage: frontend-server {start|stop|restart}" >&2
   exit 3
   ;;
esac