# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76512b30a7f0485f377eadda578f4cb32b81d3bd384fe7a97b8abc46a4cb0b2ba173ba980b7da640834cf5e87d5ade116182f588fe10da7547626ceeddf26772

test:
  secret_key_base: 447aa583c3173185d792067ec15661c109eb2ce3783aefcb230c558048a0577f96854b3c166be0d41e796b46cf7f862eeeeddc1e7047a417b317490f62124b24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
