// flow-typed signature: bcaa9a832df1c58c0f81d0b956aef083
// flow-typed version: <<STUB>>/bulma_v^0.2.3/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bulma'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bulma' {
  declare module.exports: any;
}
