// flow-typed signature: eee27fa1923a72e1fa8887b375842709
// flow-typed version: <<STUB>>/ts-loader_v^0.8.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ts-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ts-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ts-loader/resolver' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ts-loader/index' {
  declare module.exports: $Exports<'ts-loader'>;
}
declare module 'ts-loader/index.js' {
  declare module.exports: $Exports<'ts-loader'>;
}
declare module 'ts-loader/resolver.js' {
  declare module.exports: $Exports<'ts-loader/resolver'>;
}
