// flow-typed signature: 96c54d1a344a4b85b1bf005326cef36b
// flow-typed version: <<STUB>>/scss-loader_v0.0.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scss-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'scss-loader' {
  declare module.exports: any;
}
