development:
  adapter: postgresql
  encoding: unicode
  database: flox_development
  pool: 5
  username: flox_development
  password: helloworld

test:
  adapter: postgresql
  encoding: unicode
  database: flox_test
  pool: 5
  username: flox_test
  password: test
