default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  username: simpliflow
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  host: dockerhost
  password: bgduigibvgleekdibintdltcvkfluinh
  database: simpliflow_development

test:
  <<: *default
  database: simpliflow_test
  host: localhost

production:
  <<: *default
  host: simpliflow-production.crejvcdpylco.us-east-1.rds.amazonaws.com
  username: simpliflow
  database: simpliflow
